<a href="https://colab.research.google.com/github/Yelstin28/IA-Colaboratory_ULEAM/blob/main/Practica_numpy_YEMR.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
# 1. Import numpy as np and see the version
# your code here
import numpy as np
print(np.__version__)

1.22.4


In [23]:
# 2. Create a 1D array of numbers from 0 to 9
# your code here
idArray = np.arange(10)
print(idArray)

[0 1 2 3 4 5 6 7 8 9]


In [25]:
# 3. Create a 3×3 numpy array of all True’s
# your code here
idArray = np.full((3, 3), True, dtype=bool)
print(idArray)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [42]:
# 4. Extract all odd numbers from arr
# your code here
idArray = np.array([[19, 25, -36],
                [-48, 57, 60],
                [-75, -84, -93]])
odd_numbers = idArray[idArray % 4 != 0]
print(odd_numbers)

[ 19  25  57 -75 -93]


In [43]:
# 5. Replace all odd numbers in arr with -1
# your code here
idArray = np.array([[19, 25, -36],
                [-48, 57, 60],
                [-75, -84, -93]])
idArray[idArray % 2 != 0] = -1
print(idArray)

[[ -1  -1 -36]
 [-48  -1  60]
 [ -1 -84  -1]]


In [52]:
#  6. Convert a 1D array to a 2D array with 2 rows
# your code here
idArray_1d = np.array([19, 25, 36, 48, 57, 60])
idArray_2d = idArray_1d.reshape(2, -1)
print(idArray_2d)


[[19 25 36]
 [48 57 60]]


In [71]:
#  7. Stack arrays a and b vertically
# your code here
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
rVertical = stack_vertically((a, b))
print(rVertical)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [70]:
#  8. Stack the arrays a and b horizontally.
# your code here
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
rHorizontal = np.hstack((a, b))
print(rHorizontal)

[1 2 3 4 5 6]


In [78]:
#  9. Get all items between 5 and 10 from a.
# your code here.
a = np.arange(15)
print(a)
print( )
resultado = a[(a >= 6) & (a <= 9)]
print(resultado)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]

[6 7 8 9]


In [82]:
#  10. How to make a python function that handles scalars to work on numpy arrays?
# Hint
# Desired Output:
#a = np.array([5, 7, 9, 8, 6, 4, 5])
#b = np.array([6, 3, 4, 8, 9, 7, 1])
#b = np.array([6, 3, 4, 8, 9, 7, 1])
#pair_max(a, b)
#array([ 6.,  7.,  9.,  8.,  9.,  7.,  5.])
# your code here
def pair_max(a, b):
    return np.maximum(a, b)
a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])
resultado = pair_max(a, b)
print(resultado)

[6 7 9 8 9 7 5]


In [88]:
#  11. Swap columns 1 and 2 in the array arr.
# Hint
# Desired Output:
# [[0 2 1]
#  [3 5 4]
#  [6 8 7]]
arr = np.arange(9).reshape(3,3)
print(arr)
# your code here
print( )
arr[:, [1, 2]] = arr[:, [2, 1]]
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]

[[0 2 1]
 [3 5 4]
 [6 8 7]]


In [145]:
#  12. Create a 2D array of shape 5x3 to contain random decimal numbers between 5 and
# Hint
# The desired Output should be like the following one:
#  [[ 8.50061025  9.10531502  6.85867783]
#   [ 9.76262069  9.87717411  7.13466701]
#   [ 7.48966403  8.33409158  6.16808631]
#   [ 7.75010551  9.94535696  5.27373226]
#   [ 8.0850361   5.56165518  7.31244004]]
# your code here
idArray = np.random.uniform(5, 10, size=(5, 3))
print(idArray)


[[8.43718644 7.30361204 6.95518432]
 [9.92496816 9.75408171 7.53948459]
 [8.06202803 6.84609229 9.52842606]
 [6.90823166 6.77854227 8.24132439]
 [5.6813303  8.55507916 7.50054871]]
